In [3]:
import cv2

image = cv2.imread('data/1.jpg')
image = cv2.blur(image, (3, 3))
cv2.imshow('Window', image)
cv2.imwrite('data/2.jpg', image)
cv2.waitKey(0)
    

32

In [4]:

b, g, r = cv2.split(image)
cv2.imshow('b', b)
cv2.imshow('g', g)
cv2.imshow('r', r)
cv2.waitKey(0)

imagebgr = cv2.merge([r,g,b])
cv2.imshow('imagebgr', imagebgr)

#属性
print(imagebgr.shape)
print(imagebgr.size)
print(imagebgr.dtype)


32

In [1]:
import numpy as np
import cv2

imagegray = np.random.randint(0, 256, size=[256, 256], dtype=np.uint8)
imagecolor = np.random.randint(0, 256, size=[256, 256, 3], dtype=np.uint8)

cv2.imshow('imagegray', imagegray)
cv2.imshow('imagecolor', imagecolor)
cv2.waitKey(0)


-1

In [2]:
#加法运算
img1 = np.random.randint(0, 256, size=[4, 4], dtype=np.uint8)
img2 = np.random.randint(0, 256, size=[4, 4], dtype=np.uint8)
print(img1, img2, img1 + img2)
imgadd = cv2.add(img1, img2)
print(imgadd)
#减法运算
print(img1 - img2)
imgsub = cv2.subtract(img1, img2)
print(imgsub)

#乘法运算
imgarray1 = cv2.dot(img1, img2)
print(imgarray1)
imgarray2 = cv2.multiply(img1, img2)
print(imgarray2)

#除法运算
imgdiv1 = cv2.divide(img1, img2)
print(imgdiv1)

#逻辑运算
dst1 = cv2.bitwise_and(img1, img2)
dst2 = cv2.bitwise_or(img1, img2)
dst3 = cv2.bitwise_not(img1)
dst4 = cv2.bitwise_xor(img1, img2)

print(dst1, dst2, dst3, dst4)

[[ 62  51 186  94]
 [ 94 104 226 114]
 [ 86 166  38 235]
 [ 11  96 105  14]] [[161 224  29 114]
 [235 107  14 130]
 [ 61 145 225 252]
 [ 17 232  63  80]] [[223  19 215 208]
 [ 73 211 240 244]
 [147  55   7 231]
 [ 28  72 168  94]]


In [ ]:
imagegray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
imagergb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
imgcolor = cv2.cvtColor(image, cv2.COLOR_BGR2YCrCb)

hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)


